### ISSUE TITLE
Do I have to delete Cyberpunk2077.exe.plugins with the latest update?

### ISSUE THREAD

**Issue by federicotorrielli** [yamashi/PerformanceOverhaulCyberpunk#1]
Title.
I downloaded the latest from here and noticed the file changed are different, do I have to delete the old amd_patch in Cyberpunk2077.exe.plugins?
Thanks.

EDIT: i just noticed it patches two different things, can you put everything this repo patches in just one release so ppl that come here are not distracted by that?

EDIT2: No, ok, maybe it's not my fault. You just put a log in the latest release, so I think you forgot the right folder.

**Comment by yamashi** [comment]
It's better to delete if you were using the 0.1 version, otherwise you can just unzip the content and it will apply all the fixes. They are all in each release so you don't need to download multiple version.
The log file will be located either at the root directory or in bin/x64 depending on how you launch the game.

**Comment by federicotorrielli** [comment]
So I just delete the 0.1, put the performance_overhaul.dll and change the version.dll to the latest?

**Comment by yamashi** [comment]
That's right

**Comment by federicotorrielli** [comment]
Nice.
One last thing, as of EDIT2 in the first comment, you put a log in the release, and not the right dll. Check that.

**Comment by yamashi** [comment]
Oh right thanks !

**Comment by yamashi** [comment]
There you go, thanks for that!

**Comment by federicotorrielli** [comment]
Have a good day. Thanks for the nice program.
