### ISSUE TITLE
D3D12 overlay

### ISSUE THREAD

**Issue by yamashi** [yamashi/PerformanceOverhaulCyberpunk#116]
I have started work on D3D12 + Imgui https://github.com/yamashi/PerformanceOverhaulCyberpunk/tree/dx12

But I cannot figure out why it crashes. If you comment out line https://github.com/yamashi/PerformanceOverhaulCyberpunk/blob/dx12/src/overlay/Overlay.cpp#L232 it won't crash but of course it doesn't display anything.

I have tried creating my own command queue and tried using command queues the game uses but never got any luck...

**Comment by cursey** [comment]
Creating your own command queue to issue draw commands to the swapchain's back buffers will not work. You need to use the command queue created specifically for the swapchain (eg, the one used during the call to `IDXGIFactory::CreateSwapChain` or `IDXGIFactory2::CreateSwapChainForHwnd`). Game's are free to create multiple command queues so if you want the one used for the swapchain try hooking the `CreateSwapChain` methods if you're dll is loaded early enough (I haven't looked at the repo I was linked this issue since).

**Comment by yamashi** [comment]
I tried using the ones they create and it didn't work that's why I tried this as a last resort but of course that didn't work...

**Comment by cursey** [comment]
Alternatively, the correct command queue is stored within the swapchain itself. When you hook D3D12 you can scan the swapchain you make for the invisible window for a pointer to the command queue you made and store the offset. Then you can just add that offset to the real swapchain to get the real command queue.

**Comment by yamashi** [comment]
Oh I did not know that, will have to give this a shot!
