### ISSUE TITLE
Gog Proton install not working 

### ISSUE THREAD

**Issue by ArturVRSampaio** [yamashi/PerformanceOverhaulCyberpunk#119]
i followed the guide to install it on linux, but my game dont generate logs at bin/x64/plugins/cyber_engine_twerks

**Comment by LittleZen** [comment]
have you launched the game at least one time ?

**Comment by ArturVRSampaio** [comment]
yes, i launched before, and yes, i installed vcredist2019 on with winetricks

**Comment by ArturVRSampaio** [comment]
im running it with steam proton, should i run it without steam with the stand alone version?

**Comment by LittleZen** [comment]
Hmm... don't know if it could make some kind of conflict ... i'm running it with EasyPatcher and it works ... :/

**Comment by ArturVRSampaio** [comment]
the easypatcher mod is windows only right?

**Comment by LittleZen** [comment]
yes ... but i don't think is the cause, the EasyPatcher is just an installer  ... wait for yamashi ...

**Comment by ArturVRSampaio** [comment]
yup, easypatcher should not change anything... the game works, but without the mod

**Comment by LittleZen** [comment]
> yup, easypatcher should not change anything... the game works, but without the mod

Have you extract everything in x64 folder ?

**Comment by ArturVRSampaio** [comment]
yup,i have a clean x64 save where i installed it

i`m running ubuntu 20

**Comment by PoorPocketsMcNewHold** [comment]
The issue that you have here, is that you kind of cross do those two things. You use the Gog install, so you should be using winetricks BUT you run the game with Proton, so you should be using Protontricks to modify Proton own prefixes.

Basically, what you did, is indeed correctly installed vcredist2019, but on your wine prefix, not the Proton prefix that you use for the game. Try running the game with Wine to see if my assumptions is correct.

I think you can only try using protontricks non\_steam apps branch instead as said in that issue Matoking/protontricks#22

**Comment by bundyo** [comment]
Protontricks works fine with non-Steam games - you just need to find the prefix ID first - when you run it, you have this info among everything else:

```
Run winetricks for game with APPID
$ protontricks APPID COMMAND

Search installed games to find the APPID
$ protontricks -s GAME_NAME
```

Just use `protontricks -s Cyberpunk 2077` to find the ID then install what you want on it.

**Comment by Virkis** [comment]
Hi, so I found a way around this since protontricks wouldn't seem to work for me given some obscure error and just.. Yeah.

How I got this to work with Lutris and Proton-Experimental:

1. Created a new prefix in Lutris just for Cyberpunk. You may not have to do this, but me messing around all day broke something and I had to make a new prefix. You can just transfer your saves over from an existing one.
2. Start the game with Lutris pointed to it, and let it do it's thing.
3. After the game has been closed, look for "Open Bash Terminal" in Lutris while the game is selected. In new versions, it's in the popup menu next to the wine glass, on the row where "Play" is. 
4. With this terminal open, run "winetricks vcrun2019" and let it do it's thing.
5. After that, do what was lined out in the Proton guide; "The options menu for protontricks will show up again, this time select 'Run winecfg'. In the window that opens, select the 'Libraries' tab. In the dropdown on 'New override for library', select version. Click Add, then Apply and Ok."
6. Run the game again. That should do it. 

It's possible a step or two could be skipped there or streamlined into one, but I JUST got this working after trying to figure it out all day. Winetricks don't seem to open within Lutris under proton-experimental so it was just a matter of finding out how to do things in the right order. 

But hey, it works now. Now I can actually play the game.

**Comment by PoorPocketsMcNewHold** [comment]
> [**@Virkis**](https://github.com/Virkis) commented on [Dec 18, 2020, 10:54 AM GMT+1](https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/119#issuecomment-747994113):
> 
> Hi, so I found a way around this since protontricks wouldn't seem to work for me given some obscure error and just.. Yeah.
> 
> How I got this to work with Lutris and Proton-Experimental:
> 
> 1.  Created a new prefix in Lutris just for Cyberpunk. You may not have to do this, but me messing around all day broke something and I had to make a new prefix. You can just transfer your saves over from an existing one.
> 2.  Start the game with Lutris pointed to it, and let it do it's thing.
> 3.  After the game has been closed, look for "Open Bash Terminal" in Lutris while the game is selected. In new versions, it's in the popup menu next to the wine glass, on the row where "Play" is.
> 4.  With this terminal open, run "winetricks vcrun2019" and let it do it's thing.
> 5.  After that, open up a winetricks gui pointed to the Cyberpunk prefix and do what was lined out in the Proton guide; "...select 'Run winecfg'. In the window that opens, select the 'Libraries' tab. In the dropdown on 'New override for library', select version. Click Add, then Apply and Ok."
> 6.  Run the game again. That should do it.
> 
> It's possible a step or two could be skipped there or streamlined into one, but I JUST got this working after trying to figure it out all day. Winetricks don't seem to open within Lutris under proton-experimental so it was just a matter of finding out how to do things in the right order.
> 
> But hey, it works now. Now I can actually play the game.
> 
> ---
> 
> Will say that after playing around with it for a good hour almost, the game isn't NEAR as sluggish as it once was. Before everything just felt like there was this chugging temporal effect when turning, but now it's way smoother than it was previously. I'd say it was worth the hassle as I no longer have to think so hard on preempting the lag and hitching while in combat.
> 
> This is on a R7 1700 with a R9 490. Far more enjoyable experience.

![](https://user-images.githubusercontent.com/13170204/102621662-2df9f380-4140-11eb-84fb-944c214bd286.png)

From the step you have described. You seems to have indeed just edited the wine prefix that Lutris created, running with Lutris bundled wine version. It feels pretty similar to what i´ve already written in the wiki. https://github.com/yamashi/PerformanceOverhaulCyberpunk/blob/master/PROTON.md

Which is not what @ArturVRSampaio is doing. That user is running it through Steam Proton, by adding the game as a non-steam game.

**Comment by ArturVRSampaio** [comment]
> Protontricks works fine with non-Steam games - you just need to find the prefix ID first - when you run it, you have this info among everything else:
> 
> ```
> Run winetricks for game with APPID
> $ protontricks APPID COMMAND
> 
> Search installed games to find the APPID
> $ protontricks -s GAME_NAME
> ```
> 
> Just use `protontricks -s Cyberpunk 2077` to find the ID then install what you want on it.

yup, had to run 
protontricks -s Cyberpunk 2077
than copy the gameid then

protontricks gameid --gui

then i just followed the default proton install guide

IT JUST WORKS =D
