### ISSUE TITLE
AMD patch is overcomplicated and suspiciously bloated

### ISSUE THREAD

**Issue by grepwood** [yamashi/PerformanceOverhaulCyberpunk#5]
How did solving such a trivial problem warrant creating 7 files? What are you doing? I can solve this in plain C with 1 function that doesn't pull in windows.h for no reason.

```
#include <stdio.h> // PLEASE BE CONSIDERATE OF OTHERS AND NEVER INCLUDE <windows.h> NOT EVERYONE IS RUNNING A COMPROMISED SYSTEM THX
#include <stdint.h>

#define intel_slept_during_code_of_conduct_training {0x75,0x30,0x33,0xC9,0xB8,0x01,0x00,0x00,0x00,0x0F,0xA2,0x8B,0xC8,0xC1,0xF9,0x08}
#define that_long_ass_hex_length 16

char repair_icc_exe(const char * abs_path) {
  FILE * haystack = fopen(abs_path,"rb");
  char needle[that_long_ass_hex_length] = intel_slept_during_code_of_conduct_training;
  uint64_t haystack_size;
  char * haystack_in_memory = NULL;
  uint64_t bad_byte = 0;
  void * bad_byte_in_memory = NULL;
  char result = 0;
  fseek(haystack,0,SEEK_END);
  haystack_size = ftell(haystack);
  fseek(haystack,0,SEEK_SET);
  haystack_in_memory = malloc(haystack_size);
  fread(haystack_in_memory,haystack_size,1,haystack);
  bad_byte_in_memory = memmem(haystack_in_memory,haystack_size,needle,that_long_ass_hex_length);
  if(bad_byte_in_memory != NULL) {
    bad_byte = bad_byte_in_memory - haystack_in_memory;
    haystack_in_memory[bad_byte] = 0xEB;
    fclose(haystack);
    haystack = fopen(abs_path,"wb"); // never backup broken exes :)
    fwrite(haystack_in_memory,haystack_size,1,haystack);
  } else result = 1;
  fclose(haystack);
  free(haystack_in_memory);
  return result;
}
```

**Comment by BlueAmulet** [comment]
Because this does more than just patch the exe file, it patches the same code in memory at runtime, has trampoline removal, and is also a plugin system. Your solution gets removed when you validate the files on Steam and breaks updates on GOG.

**Comment by grepwood** [comment]
Great. So it's a liability for Proton.

**Comment by LeagueRaINi** [comment]
the smt patch could also be made proper by just replacing the 0x75 with a 0x74 which fixes the if statement, for anyone actually wondering what is wrong with smt in the first place
````cpp
__int64 sub_142A81400()
{
  int v10; // ecx
  __int64 result; // rax
  char Str1[4]; // [rsp+20h] [rbp-18h]
  int v13; // [rsp+24h] [rbp-14h]
  int v14; // [rsp+28h] [rbp-10h]
  char v15; // [rsp+2Ch] [rbp-Ch]
  unsigned int v16; // [rsp+40h] [rbp+8h]
  unsigned int v17; // [rsp+48h] [rbp+10h]

  sub_142A81480(&v17, &v16);
  v15 = 0;
  _RAX = 0i64;
  __asm { cpuid }
  v13 = _RDX;
  v14 = _RCX;
  *(_DWORD *)Str1 = _RBX;
  if ( strcmp(Str1, "AuthenticAMD") ) // should be '!strcmp(...)'
    return v16;
  _RAX = 1i64;
  __asm { cpuid }
  v10 = ((int)_RAX >> 8) & 0xF;
  if ( v10 == 15 ) // amd cpu's will always pass this check
    v10 = (unsigned __int8)((int)_RAX >> 20) + 15;
  result = v17; // sets return value to physical core count
  if ( v10 == 21 ) // amd cpu's will not pass this check
    result = v16;
  return result;
}```

**Comment by grepwood** [comment]
@LeagueRaINi why can't we go with an unconditional jump like 0xEB?

**Comment by LeagueRaINi** [comment]
> 
> 
> @LeagueRaINi why can't we go with an unconditional jump like 0xEB?

why would u if u can also flip 1 byte and change the if statement to what it should be?

**Comment by BlueAmulet** [comment]
Why would you use 0x74 instead of 0xEB? 0x74 just breaks it for Intel cpus and 0xEB makes it work for both cpus, and is still a 1 byte patch.

**Comment by LeagueRaINi** [comment]
> Why would you use 0x74 instead of 0xEB? 0x74 just breaks it for Intel cpus and 0xEB makes it work for both cpus, and is still a 1 byte patch.

its actually exactly the opposite. https://onlinegdb.com/g6YkIZCBI

**Comment by BlueAmulet** [comment]
![2020-12-13_214335](https://user-images.githubusercontent.com/43395286/102041298-4ce93600-3d8c-11eb-8cc0-a5919f50bdfa.png)
Here's the same function except cleaned up using the names from [ThreadCount-Win7.cpp#L69](https://github.com/GPUOpen-LibrariesAndSDKs/cpu-core-counts/blame/master/windows/ThreadCount-Win7.cpp#L69)
Ultimately the goal is to have this function return the number of logical processors.
If the vendor is not AuthenticAMD, strcmp returns a truthy value and the function returns the number of logical processors.
If it is, strcmp returns 0 and the if statement is skipped and it goes on to check the cpu family.
If the cpu family is 0x15 (old Bulldozer cpus), then count is set to logical and the function returns the number of logical processors.
Otherwise AMD users get the number of physical cores.

Flipping the if check results in AMD users returning logical cores always and Intel users always returning physical cores, since I don't think Intel has any cpus with a family of 0x15

The correct thing for both cpus to return logical cores, is to just force the jmp to always be taken with 0xEB, which gives both Intel and AMD cpus logical core counts.

**Comment by grepwood** [comment]
I see. The perfect solution would be to return the amount of cores as soon as we get the amount. No need to mess around with vendor stuff.

**Comment by LeNwAr87** [comment]
I've noticed since installing this patch to fix SMT usage on my 3600, I seem to be getting some (additional) graphical and physics glitches that I haven't noticed previously. The most noticeable graphical glitch is while I riding a motorbike I get a flickering ghost image of my character standing in the T pose on top of the bike. It doesn't really affect gameplay but I didn't notice it before the patch and I'm just concerned it may break something.

Is this a known issue or something anyone else has noticed with this?

**Comment by grepwood** [comment]
Not happening on my 2700. But, I did notice NPCs T-posing prior to applying this patch. This could be a generic feature of the game as a whole, regardless if we jack the thread amount or not.

**Comment by yamashi** [comment]
The function is invoked very rarely so being inefficient is not an issue I think.

The patch is composed of two parts:
- A loader based on the version.dll stub
- The actual patches dll

It is very bad practice to edit the exe directly, it will cause steam to think it is corrupt, breaks the signature and is not going to work after an update.

The dll technique preserves file integrity, allows more complex patches like function hooks and by using patterns will also be working even after updates.

The SMT patch is a few lines here as well, it being opensource means you can strip the parts you don't want (if you don't want them).

**Comment by LeagueRaINi** [comment]
> 
> 
> ![2020-12-13_215641](https://user-images.githubusercontent.com/43395286/102042053-2a581c80-3d8e-11eb-9215-0651fb2196a4.png)
> Here's the same function except cleaned up using the names from [ThreadCount-Win7.cpp#L69](https://github.com/GPUOpen-LibrariesAndSDKs/cpu-core-counts/blame/master/windows/ThreadCount-Win7.cpp#L69)
> Ultimately the goal is to have this function return the number of logical processors.
> 
> If the vendor is not "AuthenticAMD", strcmp returns a truthy value and the function returns the number of logical processors.
> If it is, strcmp returns 0 and the if statement is skipped and it goes on to check the cpu family.
> If the cpu family is 0x15 (old Bulldozer cpus), then count is set to logical and the function returns the number of logical processors.
> Otherwise AMD users get the number of physical cores.
> 
> Flipping the if check results in AMD users returning logical cores always and Intel users always returning physical cores, since I don't think Intel has any cpus with a family of 0x15
> 
> The correct thing for both cpus to return logical cores, is to just force the jmp/if to always be taken with 0xEB, which gives both Intel and AMD cpus logical core counts.
> 
> ![2020-12-13_220203](https://user-images.githubusercontent.com/43395286/102042358-e87ba600-3d8e-11eb-8dfe-24816faa9d0d.png)
> Using 0xEB results in this function, which is slightly inefficient, but always returns logical core count.
thats actually completely wrong maybe u shouldve actually reversed 'sub_142A81480', its the complete opposite

**Comment by BlueAmulet** [comment]
Are you capable of reading? I said as well the if statement does not pass for AMD cpus, which makes it go down to the **AMD** checks not Intel checks, as the original source code clearly indicates it's looking for AMD "Bulldozer" family.

Since it's working for Intel processors, and not for AMD, flipping it would obviously make it work for AMD processors, and not for Intel processors.

https://onlinegdb.com/BkM3ENSnv
Here's a little demo of that, right now with the original code, you get
```
vendor="GenuineIntel", family=0x6, result=Logical // Intel cpus
vendor="AuthenticAMD", family=0x15, result=Logical // AMD Bulldozer
vendor="AuthenticAMD", family=0x17, result=Physical // AMD Zen1
```
Ryzen processors get physical core count, as many other people have observed.

https://onlinegdb.com/wa3Pt-j8G
Your supposed fix of just flipping the if check with 0x74 so it goes from `if (strcmp)` to `if (!strcmp)` results in the following result:
```
vendor="GenuineIntel", family=0x6, result=Physical // Intel cpus
vendor="AuthenticAMD", family=0x15, result=Logical // AMD Bulldozer
vendor="AuthenticAMD", family=0x17, result=Logical // AMD Zen1
```
Wow look at that, Intel now gets Physical core count. Flipping it broke Intel cpus.

https://onlinegdb.com/4cqgZajeF
Using 0xEB to force the jmp/if to always be taken results in this result:
```
vendor="GenuineIntel", family=0x6, result=Logical // Intel cpus
vendor="AuthenticAMD", family=0x15, result=Logical // AMD Bulldozer
vendor="AuthenticAMD", family=0x17, result=Logical // AMD Zen1
```
Clearly the right fix, all processors get logical core count.

**Comment by yamashi** [comment]
Guys, please take it easy.
