### ISSUE TITLE
Add an option to disable AA

### ISSUE THREAD

**Issue by Kellvan** [yamashi/PerformanceOverhaulCyberpunk#68]
Currently, we need to patch the .exe to actually disable that very aggressive TXAA, which means it's impossible to use the Overhaul and disable the AA at the same time.

**Comment by Kellvan** [comment]
It will also speed things up since the AA here is heavy AF.

**Comment by Kirides** [comment]
The game is crafted with this antialiasing in mind. Without it you get _*VERY*_ ugly artifacts all over the place if you use screen space reflections

This is an example of the game without antialiasing:
![image](https://user-images.githubusercontent.com/13602143/102257908-a036c200-3f0d-11eb-9125-19c2c82aa964.png)

**Comment by yamashi** [comment]
It is indeed pretty horrible...

**Comment by PastDef** [comment]
@Kellvan Here is a way to disable TAA without having to edit the .exe:

Create (or open) the Cyberpunk 2077\engine\config\platform\pc\user.ini file, and add the following inside it:

[Developer/FeatureToggles]
Antialiasing = false
ScreenSpaceReflection = false

AA will be disabled and it will also disable SSR to prevent most artifacts.
There will still be some artifacts since the game is designed to ru with TAA enabled.
Also note that in 1.04 there was extra sharpening added into the game what to my knowledge cant be disabled.

**Comment by HeroOfOlympus** [comment]
One question on this topic. Do DLSS disable AA or wouldn't it look close enough with disabled AA and turned on DLSS?

**Comment by Kirides** [comment]
DLSS is automatically disabled if AA is disabled.

Atleast this is what i see on my system when disabling AA.
