### ISSUE TITLE
At a loss here

### ISSUE THREAD

**Issue by Eleiyas** [yamashi/PerformanceOverhaulCyberpunk#77]
I tried the HexEdit before I found this "fixpack" and I've also previously tried the "memory_pool.csv" fix as well:
Ryzen 7 2700X
Gigabyte Vega64
64GB RAM
nVME install drive

No matter what I do or what I set the in-game settings to, I am at around 60FPS in the Badlands (Panam's area), 35FPS in low-density town areas, then anywhere from 10-20FPS in high-density town areas (yes, I have hit 10FPS). 
The FPS also takes a massive hit when driving, especially fast. 

CPU is at around 90-95% and GPU is at 80-85% usage when the game is running. FPS though, whether I put everything to lowest possible settings, or ultra are always the same.

This "fixpack" did improve FPS in certain areas (Badlands) for sure, I was amazed Steam's overlay even showed 65FPS for a brief moment, but in towns it seems to be either the same, or if not slightly worse FPS.

With the fact my CPU is almost maxing-out, while my GPU has headroom, it seems to be a CPU-bottleneck, but I just find that so hard to believe.

The only other thing I can think of, is that it's some piece of software on my PC causing an issue, like keyboard software, or Razer Synapse, which is known to cause issues with other games, I just don't know.

**Comment by xdtrammell** [comment]
You are definitely having a cpu bottleneck. I have the i7 7700k which performs similar to your CPU in gaming, I have similar issues as you not dips as low as 10 but I have a 3080 so the cpu is a major bottleneck for me.

**Comment by Eleiyas** [comment]
> You are definitely having a cpu bottleneck. I have the i7 7700k which performs similar to your CPU in gaming, I have similar issues as you not dips as low as 10 but I have a 3080 so the cpu is a major bottleneck for me.

how on earth can a 2700X perform this badly on this game!? 8 cores at 4.2Ghz and it lags like that? how terribly optimised is this game then? my lord

**Comment by snailzrus** [comment]
> You are definitely having a cpu bottleneck. I have the i7 7700k which performs similar to your CPU in gaming, I have similar issues as you not dips as low as 10 but I have a 3080 so the cpu is a major bottleneck for me.

CPU bottleneck doesn't make sense. It's an 8-core 16 thread CPU. Unless you've got the thing seriously power limited aka, undervolted, then I don't see how that would be causing this problem for you. The usage seems really high for no good reason. Cyberpunk is definitely more of a GPU bottlenecked game anyways.

Check your GPU drivers are up to date. maybe reinstall them (clear with DDU first). After that, do a system reboot, run cinebench while watching your CPU core clocks with something like hwinfo64. If the cores are boosting to what you'd expect, and your cinebench score is what other people with a 2700x get, then check your memory speed too. Ryzen is very sensitive to memory latency, so make sure it's at least using XMP, and if not, try to make sure it's got decent timings. You can use a guide with the ryzen dram calculator to help tune your memory if needed.

If everything about your system performs as expected and it's just this one game that's messed up, then reinstall the game.

This performance patch will NOT WORK if you're using the HEX modified exe. You'll have to run a file verification through steam, or manually undo the HEX edit.

It's not apples to apples, but I have a GTX 1080, which performs similarly to a Vega64 in most games. It's constantly pegged at 100% utilization while playing cyberpunk. It's paired with a 3950x. Yes, a more beefy CPU, but it's double the core and thread count with a modest boost to IPC and core clock, but it's not leagues different in gaming. The 3950x performs just a hair better than a 2700x in most games. I see about 38% CPU utilization using my 3950x, so cut it in half and I should see about 76% utilization if I was using a 3700x instead. Take off the extra core clock and IPC, and maybe 85%.

**Comment by Eleiyas** [comment]
> > You are definitely having a cpu bottleneck. I have the i7 7700k which performs similar to your CPU in gaming, I have similar issues as you not dips as low as 10 but I have a 3080 so the cpu is a major bottleneck for me.
> 
> CPU bottleneck doesn't make sense. It's an 8-core 16 thread CPU. Unless you've got the thing seriously power limited aka, undervolted, then I don't see how that would be causing this problem for you. The usage seems really high for no good reason. Cyberpunk is definitely more of a GPU bottlenecked game anyways.
> 
> Check your GPU drivers are up to date. maybe reinstall them (clear with DDU first). After that, do a system reboot, run cinebench while watching your CPU core clocks with something like hwinfo64. If the cores are boosting to what you'd expect, and your cinebench score is what other people with a 2700x get, then check your memory speed too. Ryzen is very sensitive to memory latency, so make sure it's at least using XMP, and if not, try to make sure it's got decent timings. You can use a guide with the ryzen dram calculator to help tune your memory if needed.
> 
> If everything about your system performs as expected and it's just this one game that's messed up, then reinstall the game.
> 
> This performance patch will NOT WORK if you're using the HEX modified exe. You'll have to run a file verification through steam, or manually undo the HEX edit.
> 
> It's not apples to apples, but I have a GTX 1080, which performs similarly to a Vega64 in most games. It's constantly pegged at 100% utilization while playing cyberpunk. It's paired with a 3950x. Yes, a more beefy CPU, but it's double the core and thread count with a modest boost to IPC and core clock, but it's not leagues different in gaming. The 3950x performs just a hair better than a 2700x in most games. I see about 38% CPU utilization using my 3950x, so cut it in half and I should see about 76% utilization if I was using a 3700x instead. Take off the extra core clock and IPC, and maybe 85%.

well, well, well, thanks to you giving me something to check, seems I did indeed find an issue.
I got 1308 in Cinebench R15, when I should have been hitting 1800 score, so something is definitely not right. I only turbo'd up to 3.9Ghz as well, when I should easily be hitting 4.2Ghz.

I did just update my chipset drivers and BIOS, so I obviously need to go do some tinkering in the settings.

**Comment by snailzrus** [comment]
Glad I could help!

**Comment by OLoKo64** [comment]
Yeah, I have a GTX 1060 and a Ryzen 7 2700x.
I vet around 30-50 fps in the city, but my CPU is at 30-60% all times, not at all close to 100%, sometimes my GPU utilization drops too but is not a CPU bottleneck. 

Like said above, a 8c/16t CPU should not bottleneck.

Hope you find what's wrong with your system.

Being honest, this patch didn't help that much to me, as my GPU is at 100%, but the CPU utilization stabilized a lot.

**Comment by Eleiyas** [comment]
> Glad I could help!



> Yeah, I have a GTX 1060 and a Ryzen 7 2700x.
> I get around 30-50 fps in the city, but my CPU is at 30-60% all times, not at all close to 100%, sometimes my GPU utilization drops too but is not a CPU bottleneck.
> 
> Like said above, a 8c/16t CPU should not bottleneck.
> 
> Hope you find what's wrong with your system.
> 
> Being honest, this patch didn't help that much to me, as my GPU is at 100%, but the CPU utilization stabilized a lot.


I have never had luck OC'ing this CPU, but I am getting around 4Ghz on all cores stable. I upped my RAM to the rated 3000Mhz (used to have 16GB 3200Mhz, but changed to 64GB 3000Mhz ) and it most certainly has helped. 
I'm not dipping into the 10-15FPS range anymore and the lower-density city areas are hanging around 40FPS, rather than 25-35FPS now. 

So, it could be that my RAM is bottle-necking my CPU (even though 3000Mhz should be more than enough for any game), or it comes down to CDPR releasing a buggy, unfinished and unoptimised game.

Seeing as there are people with Ryzen 5000-series CPUs and RTX3080s saying that they are also sometimes dipping below 60FPS, my guess is that it's the game, more than the hardware.

**Comment by ArturVRSampaio** [comment]
my rig is a Ryzen 72700, 16gb Ram, 1060 3gb and i'm using ubuntu 20 (playing with proton) 

i'm running something like 50 ~ 60 fps on medium, the CPU usage is about 20% ~30%, check if you have anything running on the back, maybe try a fresh install of your OS and check the drivers

**Comment by snailzrus** [comment]
> I upped my RAM to the rated 3000Mhz (used to have 16GB 3200Mhz, but changed to 64GB 3000Mhz ) and it most certainly has helped.

Yeah if "upped" is 3000mhz, then whatever it was before was absolutely killing your performance.

> So, it could be that my RAM is bottle-necking my CPU (even though 3000Mhz should be more than enough for any game), or it comes down to CDPR releasing a buggy, unfinished and unoptimised game.

It was absolutely your RAM that was the bottleneck. Even 3000mhz is still not very fast, and likely not fast enough to stop being the bottleneck. Your problem here is memory access time. Cyberpunk uses very little system memory, but is heavily dependent on quick access to it. I see about 4GB of usage, with and without mods to open up allocation of more to the game.

As you've only said 3000mhz, I don't know your memory timings, but they're probably not great. On a 2700x, I'd personally say 3200mhz 16-18-18-39 is the "minimum" for gaming and workstation use since anything slower is absolutely going to limit your CPUs capabilities. You can look up how memory scaling effects the 2700x and see how critical just MHz is, and then dig a bit more to find how timings affects it too.


> Seeing as there are people with Ryzen 5000-series CPUs and RTX3080s saying that they are also sometimes dipping below 60FPS, my guess is that it's the game, more than the hardware.

Those folks have something weird going on too and I wouldn't blame the game for it. I don't know what resolution they were at, or settings. For all we know they could be running 8k lol.

My best guess is that it's probably a similar scenario to your issue. Maybe a new build and they forgot to turn on XMP. Maybe they did a windows update recently, or chipset, and it made something unstable and the memory flopped back to XMP off. I've had that happen before.

Like I said before though, I'm on a 3950x at 38% CPU utilization with a GTX 1080 (non-ti) at 100% utilization. Memory is 64GB of 3600 cl 16-16-18-36 (with other various subtimings tightened further too). At 2560x1080 (playing on a 3440x1440 monitor, but heavily GPU bottlenecked), I'm getting 60fps on mostly high/ultra settings. All I have turned down is the first 4 toggles for film grain and chromatic whatever, then screen space reflections is off cause it tanks my performance just putting it on low. Maybe turn that off? I'm certain people should be able to get 60fps with a 5000 series CPU and a 3080. If they were using my RAM settings, resolution, and game settings, I'd wager they'd get over 120fps.

Either way, yes, the game can be optimized better for sure. The maker of this mod is doing God's work here lol. But seeing performance on your PC that isn't in line with what other people who have similarly spec'd PCs isn't the game's fault. It's hardware/drivers.

Hope you can sort it out a bit better with a ram overclock. I highly recommend you put some time into researching how memory speed and timings effect the performance scaling of your CPU generation, and then look to use the dram calculator to give yourself a boost if possible.

Also check out the digital foundry settings guide video. They tested literally everything to see how it effects performance and picture quality. My only change to it was turning off screen space reflections entirely.

**Comment by snailzrus** [comment]
@yamashi this can probably be closed. It's more tech support than related to your mod
